#!/usr/bin/env python3
"""
update_mocs.py

Semi-automates MOC (Map of Content) maintenance.

For each note that contains a [[link]] back to a MOC (e.g. [[Backend]]),
this script checks whether that note is already listed in the MOC. If not,
it appends a "## Suggested additions" section to the MOC file with the
missing notes, so a human can review and promote them to the main body.

It also flags MOC pages whose `last_reviewed` frontmatter date is older
than STALE_DAYS days.

Usage:
    python3 scripts/update_mocs.py [--dry-run]

Flags:
    --dry-run   Print what would change without writing any files.
"""

import re
import sys
from datetime import date, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTES_DIR = REPO_ROOT / "Notes"
STALE_DAYS = 90
DRY_RUN = "--dry-run" in sys.argv

# Frontmatter block
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
LAST_REVIEWED_RE = re.compile(r"last_reviewed:\s*(\d{4}-\d{2}(?:-\d{2})?)")
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:[#|][^\]]*)?\]\]")
SUGGESTED_HEADER = "## Suggested additions"
SUGGESTED_MARKER = "<!-- auto-generated by update_mocs.py -->"


def read_notes() -> dict[str, str]:
    """Return {stem: content} for all notes."""
    return {f.stem: f.read_text(encoding="utf-8") for f in sorted(NOTES_DIR.glob("*.md"))}


STATUS_RE = re.compile(r"^---\s*\n.*?^status:\s*(\S+).*?^---", re.DOTALL | re.MULTILINE)


def get_status(content: str) -> str:
    m = STATUS_RE.search(content)
    return m.group(1).strip() if m else "stable"


def is_moc(stem: str, content: str) -> bool:
    """Heuristic: a note is a MOC if its name contains 'MOC', 'Map', 'Index',
    or if it has a section that mostly contains wikilinks."""
    if any(kw in stem for kw in ("MOC", "Map", "Index", "Overview")):
        return True
    # Count wikilinks vs total non-empty lines
    lines = [l for l in content.splitlines() if l.strip()]
    link_lines = [l for l in lines if WIKILINK_RE.search(l)]
    return len(lines) > 2 and len(link_lines) / len(lines) > 0.4


def links_in(content: str) -> list[str]:
    return [m.group(1).strip() for m in WIKILINK_RE.finditer(content)]


def listed_in_moc(moc_content: str) -> set[str]:
    """Return lowercased stems of notes already listed in the MOC body
    (exclude the Suggested additions section)."""
    body = moc_content.split(SUGGESTED_HEADER)[0]
    return {t.lower() for t in links_in(body)}


def check_staleness(stem: str, content: str) -> None:
    match = LAST_REVIEWED_RE.search(content)
    if not match:
        print(f"  ⚠  MOC '{stem}' has no last_reviewed date.")
        return
    raw = match.group(1)
    # Accept YYYY-MM or YYYY-MM-DD
    try:
        reviewed = datetime.strptime(raw, "%Y-%m-%d").date() if len(raw) == 10 \
                   else datetime.strptime(raw + "-01", "%Y-%m-%d").date()
    except ValueError:
        print(f"  ⚠  MOC '{stem}' has unreadable last_reviewed: {raw}")
        return
    age = (date.today() - reviewed).days
    if age > STALE_DAYS:
        print(f"  ⚠  MOC '{stem}' last reviewed {reviewed} ({age} days ago) — consider updating.")


def build_suggested_section(missing: list[str]) -> str:
    lines = [SUGGESTED_HEADER, SUGGESTED_MARKER, ""]
    lines += [f"- [[{name}]]" for name in sorted(missing)]
    lines += [""]
    return "\n".join(lines)


def update_moc(stem: str, content: str, missing: list[str]) -> str:
    """Return updated MOC content with the Suggested additions section replaced."""
    # Remove old auto-generated section if present
    if SUGGESTED_HEADER in content:
        content = content[:content.index(SUGGESTED_HEADER)].rstrip() + "\n"

    if missing:
        content = content.rstrip() + "\n\n" + build_suggested_section(missing)

    return content


def main() -> int:
    notes = read_notes()
    moc_stems = {stem for stem, content in notes.items() if is_moc(stem, content)}

    if not moc_stems:
        print("No MOC pages detected.")
        return 0

    print(f"Detected MOC pages: {sorted(moc_stems)}\n")

    changes = 0
    for moc_stem in sorted(moc_stems):
        moc_content = notes[moc_stem]
        check_staleness(moc_stem, moc_content)
        already_listed = listed_in_moc(moc_content)

        # Find notes that link TO this MOC but aren't listed IN it
        missing = []
        for stem, content in notes.items():
            if stem == moc_stem:
                continue
            # Skip draft notes — they are not ready to be listed in a MOC yet
            if get_status(content) == "draft":
                continue
            outbound = {t.lower() for t in links_in(content)}
            if moc_stem.lower() in outbound and stem.lower() not in already_listed:
                missing.append(stem)

        if missing:
            print(f"  MOC '{moc_stem}': {len(missing)} unlisted note(s) → {missing}")
            updated = update_moc(moc_stem, moc_content, missing)
            if not DRY_RUN:
                (NOTES_DIR / f"{moc_stem}.md").write_text(updated, encoding="utf-8")
                print(f"    ✓ Written.")
            else:
                print(f"    (dry-run, not written)")
            changes += 1
        else:
            print(f"  MOC '{moc_stem}': up to date.")

    print(f"\nDone. {changes} MOC(s) updated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
